/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea3476182f82d390e77c9df
*
* You will get 10% discount for each one of your friends
* 
*/
/**

  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
                                                                                     
                                                                                   
 *  DO NOT EDIT HIS FILE!!
 * 
 *  FOR CUSTOMIZE DB SCHEMA PLEASE EDIT db/CarHexa_db_customSchema.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const createUser = require('../security/security.js');

const db_CarHexa_db_schema = [];
const db_CarHexa_db = [];

/**
 * SCHEMA DB CarHexa_db
 */



 /**
  * Driver
  */
db_CarHexa_db_schema.Driver = new mongoose.Schema({
	Address: {
		type: 'String'
	},
	FisrtName: {
		type: 'String'
	},
	LastName: {
		type: 'String'
	},
	License: {
		type: 'String'
	},
	Ratings: {
		type: 'String'
	},
	//RELATIONS
	_passenger: {
		type: Schema.ObjectId,
		ref : "Passenger"
	},
	
	
	//EXTERNAL RELATIONS
	/*
	_drivers: {
		type: Schema.ObjectId,
		ref : "Passenger"
	},
	*/
});


 /**
  * Passenger
  */
db_CarHexa_db_schema.Passenger = new mongoose.Schema({
	Address: {
		type: 'String'
	},
	FirstName: {
		type: 'String'
	},
	LastName: {
		type: 'String'
	},
	PhoneNumber: {
		type: 'String'
	},
	//RELATIONS
	_drivers: {
		type: Schema.ObjectId,
		ref : "Driver"
	},
	
	
	//EXTERNAL RELATIONS
	/*
	_passenger: {
		type: Schema.ObjectId,
		ref : "Driver"
	},
	*/
});


 /**
  * User
  */
db_CarHexa_db_schema.User = new mongoose.Schema({
	mail: {
		type: 'String'
	},
	name: {
		type: 'String'
	},
	password: {
		type: 'String', 
		required : true
	},
	roles: [{
		type: 'String'
	}],
	surname: {
		type: 'String'
	},
	username: {
		type: 'String', 
		required : true
	},
	//RELATIONS
	
	
	//EXTERNAL RELATIONS
	/*
	*/
});



// Import schema customization
require('./CarHexa_db_customSchema.js');
var CarHexa_db_model = require('./CarHexa_db_crud.js');

// Declare mongoose model

db_CarHexa_db.Driver = CarHexa_db_model.connection.model('Driver', db_CarHexa_db_schema.Driver );
db_CarHexa_db.Passenger = CarHexa_db_model.connection.model('Passenger', db_CarHexa_db_schema.Passenger );
db_CarHexa_db.User = CarHexa_db_model.connection.model('User', db_CarHexa_db_schema.User );

module.exports = db_CarHexa_db;

// Create ADMIN user if does not exist
createUser.createUser();
